# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "container-sample-dev-tfstate-987359833978-1"
    encrypt = true
    key     = "tfstate/container-sample/dev/modules/ecr/terraform.tfstate"
    region  = "ap-northeast-1"
  }
}
